/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package test.java.javachessproject;

import main.java.javachessproject.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    private void assertNotNull(String greeting, String string) {
    }
}
