package test.java;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import main.java.*;;

class AppTest {
    @Test
    void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    private void assertNotNull(String greeting, String string) {
    }
}
